### ISSUE TITLE
No parameter set for mitcr?

### ISSUE THREAD

**Issue by sdwfrost** [mikessh/aging-study#1]
Dear @mikessh 

Great job BTW on putting this all online. I'm trying to rerun using `process.sh`, but the parameter set file `age-pset` is missing, and I can't find sufficient detail in the [paper](http://www.jimmunol.org/content/196/12/5005.long). Would you mind adding?

**Comment by mikessh** [comment]
Thanks a lot, fixed it!

**Comment by sdwfrost** [comment]
Thanks @mikessh!
